---
- name: domain_id | check for pollution
  assert:
    that: >
      (libvirt_result_domain_name is not defined)
      or (libvirt_domain_name is not defined)
      or (libvirt_domain_name != libvirt_result_domain_name)
  tags:
  - facts

- name: domain_id | create uuid
  command: uuidgen
  changed_when: no
  register: libvirt_domain_uuid_result
  when: >
    (libvirt_domain_name is not defined)
    or (not libvirt_domain_name)
  tags:
  - facts

- name: domain_id | extract
  set_fact:
    libvirt_result_domain_name: >
      {{
        libvirt_domain_name
          if (libvirt_domain_name is defined)
            and libvirt_domain_name
          else
        libvirt_domain_uuid_result.stdout | trim
      }}
  tags:
  - facts
